version: 0.2

phases:

  install:
    runtime-versions:
      java: openjdk11
      python: 3.8

    commands:
      - pip3 install aws-sam-cli
      - pip3 install requests

  build:
    commands:
      - sam build
      - sam package --s3-bucket $S3_BUCKET --output-template-file packaged.yaml

artifacts:
  files:
    - packaged.yaml